export const Data = [
    {
        name:"Pizza",
        brand:"Dominose",
        img:food1
    },
    {
        name:"Burger",
        brand:"KFC",
        img:food2
    },
    {
        name:"Dosa",
        brand:"Anna",
        img:food3
    },
    {
        name:"Biryani",
        brand:"Nawab",
        img:food4
    },
    {
        name:"Paneer",
        brand:"Shahi",
        img:food5
    },
    {
        name:"Cake",
        brand:"SoftCake",
        img:food6
    },
]
